language: java
sudo: required
script:
  - node -v
  - npm -v 
  - which node
  - nvm install v6.12.3
  - rm -rf /home/travis/.nvm
  - sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs phantomjs yarn
  - sudo yarn global add bower
  - sudo npm install -g ember-cli@2.15.1
  - node -v
  - npm -v
  - yarn -v
  - bower -v
  - java -v
  - ember -v
  - ./scripts/build
  - java -version
  - gradle -v
  
deploy:
  provider: releases
  skip_cleanup: true # Otherwise Travis Cleans all the files created during build
  overwrite: true
  api_key:
    secure: QGw001eXW+rgBpNOl7QqG4I6329tdDLEpRsx2zw12T3Kv1tscUJN2Uuj/apxFzN0ynakGIm1+HOuhqCRikFd0As2iSkNkahSuP7ciqfl9g8YC2lhKUqonY1ihbnsIVUa5dX97XVIxiAu0ye1cDaPlsmgLaewZ66YnMje6uhX+nEhnqlAFksj8+iA6NlOJoT0zLk4wX2PBDRIjlbmtVXxRpCaqOnDmTVa0+OQC6Ebn3NwPQI0Q/EHn/Iu2V2L2LBD1AeqP9E5gdx94V23Vf+zxgdqNVV7eOzWHmMI0anyNLFuQucgfOwjrzdKo9mhWDFrjrJGLYzLeOaW+/27khcPkFP/v9bjWWR671vzqHYc9QJzkT2OJ1PwZ1yAs+ETsiPpxBecD4e8XsLIhUG1M2CU+LCF0nKgJnDxDdvQbmk8wylIaNkrmUVyRv6rFLjRsV6fHVR0RnsUjW7lvhzMud3R2El1Z1GiSNagOft/oT4C6UCs4bKdC0kGRnJ5ZlZ7zVGVk939qXUyvAt+el77XcbvSlebwiFj1YEruvM5k9dqar1M54Yqcxnx99e4Ce1nSomGR8njromLleRMKzRUKF9cvSkYqvxnSiI5u3fHB4guV8f4Py0u1cO8KilRPmsk3B5XNocjvQxpoKaNrgBFq+yi4bqoC1kztRcAXL6ZNFg471k=
  file_glob: true
  file: dist/cattle-*.tar.gz
  on:
    repo: vharsh/cattle
    branch: master
