language: java
script: "./scripts/build"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OIB+Wj85tB7Zu3tH1akdh34x9CH5G/edWdeylL7MPD+8fnDH/L2UMaA01/z4yYPn09cfpedwtTTYf2GYt8/E9hiuP1/PJTjI8xslE5IASMa8wuPdkS5Z85XHzGUybsbY1H1aJHIV2ldJv35QUb3mdAStYShoY5w1mGThalwoGr5AJlnYFpGdC304UHVRj2x0FU0KELDFHvoS9qX68N7VKMtw941NDpPpSjQgZSYAZtTK32PrWr6r90xmJoIiUF5v5UI8g//GgEYIWe9uq7s/7p1eGoWOQfvhBmMP0V0Qx7+GYJV7WcTA4Z1rpcYMcJ+6qBmmF/FU6K7gea+r1QPblhgCK3ULyNfbD438Kx2HxdcBFgYG7Qf1sy8ab0xsPn5D+20i1QdPDJvA96ZZq/eoHv2/TV1Wf90YopuHG3oClQ+olhUTqMBWeUAlJBLDgTYxDGYyyd2EA3S+U1HchoG0ARKkM7EQfulWaluzNpU73jNzIZ6XM9DYs3LbtoI27Pv/HvpZy51LgpRnZe3GhVrq1Hl4QrVl+fdf4zaedhROYyzFnhul/tva7c7yRicoEOm+WnTzcAuehuCF9oDWfhUehlLXGWfkc5dT9gBMFPrXXV9AAwWZuX7Y0d2MgWxFXx+DrXTLeQXlITuhi3RudqGa0QetapdoYH1yryTNA+/RBRY=
file_glob: true
file: "dist/cattle-*.tar.gz"
  on:
    repo: vharsh/cattle
